### ISSUE TITLE
Integração com PIX 

### ISSUE THREAD

**Issue by wisley7l** [ecomplus/app-infinitepay#84]
Referências: https://www.infinitepay.io/docs#autorizando-pagamento-utilizando-o-pix

> Em termos gerais, basta seguir os passos abaixo:

> * Fornecer os dados específicos da transação com PIX no endpoint da /v2/transactions; Mais detalhes [aqui](https://www.infinitepay.io/docs#autorizando-pagamento-utilizando-o-pix).

> * O response dessa chamada contém o br_code que deve ser usado para renderizar o QRCode de pagamento ao comprador; Mais detalhes [aqui](https://www.infinitepay.io/docs#renderizando-qrcode-apos-a-transacao-pix).

> * Quando o pagamento for confirmado, nosso sistema fará uma requisição no endereço informado no callback_url(informado na criação da transação PIX). Para validar o payload basta seguir os passos descritos [aqui](https://www.infinitepay.io/docs#validacao-de-callback-do-pix-pago).

> * Lembramos que é muito importante que o lojista tenha uma chave PIX habilitada no App InfinitePay para que o pagamento com PIX funcione corretamente.

**Comment by matheusgnreis** [comment]
Bom dia, quando configura desconto no pix, ele está aplicando também para cartão de crédito.
