### ISSUE TITLE
Campo parcela mínima não sendo utilizado para listar parcelas

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-infinitepay#89]
**Descreva o bug**
Não está sendo usado o campo min_installment que está para configuração no app. No caso, tem lojas que configuraram com 20 e o produto custa 39 reais, deveria ter apenas 1 parcela de 39 e no checkout está sendo mostrado 3 parcelas

**Comment by wisley7l** [comment]
@matheusgnreis subi a correção.
